# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window_test.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(729, 516)
        MainWindow.setAnimated(True)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowNestedDocks|QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.mdiArea = QtGui.QMdiArea(self.centralwidget)
        self.mdiArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mdiArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        brush = QtGui.QBrush(QtGui.QColor(202, 202, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.mdiArea.setBackground(brush)
        self.mdiArea.setObjectName(_fromUtf8("mdiArea"))
        self.verticalLayout_2.addWidget(self.mdiArea)
        MainWindow.setCentralWidget(self.centralwidget)
        self.dockWidget = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.dockWidget.sizePolicy().hasHeightForWidth())
        self.dockWidget.setSizePolicy(sizePolicy)
        self.dockWidget.setMinimumSize(QtCore.QSize(198, 142))
        self.dockWidget.setFeatures(QtGui.QDockWidget.DockWidgetFloatable|QtGui.QDockWidget.DockWidgetMovable)
        self.dockWidget.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.dockWidget.setObjectName(_fromUtf8("dockWidget"))
        self.dockWidgetContents_2 = QtGui.QWidget()
        self.dockWidgetContents_2.setObjectName(_fromUtf8("dockWidgetContents_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.dockWidgetContents_2)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gb_communication = QtGui.QFrame(self.dockWidgetContents_2)
        self.gb_communication.setEnabled(False)
        self.gb_communication.setAutoFillBackground(False)
        self.gb_communication.setObjectName(_fromUtf8("gb_communication"))
        self.gridLayout = QtGui.QGridLayout(self.gb_communication)
        self.gridLayout.setMargin(0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.pb_send = QtGui.QPushButton(self.gb_communication)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_send.sizePolicy().hasHeightForWidth())
        self.pb_send.setSizePolicy(sizePolicy)
        self.pb_send.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pb_send.setBaseSize(QtCore.QSize(30, 0))
        self.pb_send.setObjectName(_fromUtf8("pb_send"))
        self.gridLayout.addWidget(self.pb_send, 1, 1, 1, 1)
        self.pb_clear = QtGui.QPushButton(self.gb_communication)
        self.pb_clear.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pb_clear.setObjectName(_fromUtf8("pb_clear"))
        self.gridLayout.addWidget(self.pb_clear, 1, 2, 1, 1)
        self.en_send = QtGui.QLineEdit(self.gb_communication)
        self.en_send.setMinimumSize(QtCore.QSize(100, 0))
        self.en_send.setObjectName(_fromUtf8("en_send"))
        self.gridLayout.addWidget(self.en_send, 1, 0, 1, 1)
        self.lw_received = QtGui.QListWidget(self.gb_communication)
        self.lw_received.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.lw_received.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.lw_received.setObjectName(_fromUtf8("lw_received"))
        self.gridLayout.addWidget(self.lw_received, 0, 0, 1, 3)
        self.gridLayout.setColumnStretch(0, 10)
        self.verticalLayout_3.addWidget(self.gb_communication)
        self.dockWidget.setWidget(self.dockWidgetContents_2)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockWidget)
        self.control_dock = QtGui.QDockWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.control_dock.sizePolicy().hasHeightForWidth())
        self.control_dock.setSizePolicy(sizePolicy)
        self.control_dock.setMinimumSize(QtCore.QSize(98, 216))
        self.control_dock.setFloating(False)
        self.control_dock.setFeatures(QtGui.QDockWidget.DockWidgetMovable)
        self.control_dock.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea|QtCore.Qt.RightDockWidgetArea)
        self.control_dock.setObjectName(_fromUtf8("control_dock"))
        self.dockWidgetContents_3 = QtGui.QWidget()
        self.dockWidgetContents_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.dockWidgetContents_3.setObjectName(_fromUtf8("dockWidgetContents_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.dockWidgetContents_3)
        self.verticalLayout_4.setMargin(9)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.pb_connect = QtGui.QPushButton(self.dockWidgetContents_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_connect.sizePolicy().hasHeightForWidth())
        self.pb_connect.setSizePolicy(sizePolicy)
        self.pb_connect.setMinimumSize(QtCore.QSize(80, 0))
        self.pb_connect.setToolTip(_fromUtf8(""))
        self.pb_connect.setObjectName(_fromUtf8("pb_connect"))
        self.verticalLayout_4.addWidget(self.pb_connect)
        self.pb_disconnect = QtGui.QPushButton(self.dockWidgetContents_3)
        self.pb_disconnect.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_disconnect.sizePolicy().hasHeightForWidth())
        self.pb_disconnect.setSizePolicy(sizePolicy)
        self.pb_disconnect.setToolTip(_fromUtf8(""))
        self.pb_disconnect.setObjectName(_fromUtf8("pb_disconnect"))
        self.verticalLayout_4.addWidget(self.pb_disconnect)
        self.line_3 = QtGui.QFrame(self.dockWidgetContents_3)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout_4.addWidget(self.line_3)
        self.pb_manualControl = QtGui.QPushButton(self.dockWidgetContents_3)
        self.pb_manualControl.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_manualControl.sizePolicy().hasHeightForWidth())
        self.pb_manualControl.setSizePolicy(sizePolicy)
        self.pb_manualControl.setMinimumSize(QtCore.QSize(80, 0))
        self.pb_manualControl.setObjectName(_fromUtf8("pb_manualControl"))
        self.verticalLayout_4.addWidget(self.pb_manualControl)
        self.pb_editor = QtGui.QPushButton(self.dockWidgetContents_3)
        self.pb_editor.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_editor.sizePolicy().hasHeightForWidth())
        self.pb_editor.setSizePolicy(sizePolicy)
        self.pb_editor.setMinimumSize(QtCore.QSize(80, 0))
        self.pb_editor.setObjectName(_fromUtf8("pb_editor"))
        self.verticalLayout_4.addWidget(self.pb_editor)
        self.pb_postionList = QtGui.QPushButton(self.dockWidgetContents_3)
        self.pb_postionList.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_postionList.sizePolicy().hasHeightForWidth())
        self.pb_postionList.setSizePolicy(sizePolicy)
        self.pb_postionList.setMinimumSize(QtCore.QSize(80, 0))
        self.pb_postionList.setAutoExclusive(False)
        self.pb_postionList.setObjectName(_fromUtf8("pb_postionList"))
        self.verticalLayout_4.addWidget(self.pb_postionList)
        self.pb_IOconsole = QtGui.QPushButton(self.dockWidgetContents_3)
        self.pb_IOconsole.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_IOconsole.sizePolicy().hasHeightForWidth())
        self.pb_IOconsole.setSizePolicy(sizePolicy)
        self.pb_IOconsole.setMinimumSize(QtCore.QSize(80, 0))
        self.pb_IOconsole.setObjectName(_fromUtf8("pb_IOconsole"))
        self.verticalLayout_4.addWidget(self.pb_IOconsole)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem)
        self.control_dock.setWidget(self.dockWidgetContents_3)
        MainWindow.addDockWidget(QtCore.Qt.DockWidgetArea(2), self.control_dock)
        self.toolBar = QtGui.QToolBar(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toolBar.sizePolicy().hasHeightForWidth())
        self.toolBar.setSizePolicy(sizePolicy)
        self.toolBar.setMovable(False)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 729, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSetting = QtGui.QMenu(self.menubar)
        self.menuSetting.setObjectName(_fromUtf8("menuSetting"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuRun = QtGui.QMenu(self.menubar)
        self.menuRun.setObjectName(_fromUtf8("menuRun"))
        MainWindow.setMenuBar(self.menubar)
        self.actionSerial_port = QtGui.QAction(MainWindow)
        self.actionSerial_port.setObjectName(_fromUtf8("actionSerial_port"))
        self.actionManual_control = QtGui.QAction(MainWindow)
        self.actionManual_control.setEnabled(False)
        self.actionManual_control.setObjectName(_fromUtf8("actionManual_control"))
        self.actionEditor = QtGui.QAction(MainWindow)
        self.actionEditor.setEnabled(False)
        self.actionEditor.setObjectName(_fromUtf8("actionEditor"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionI_O_console = QtGui.QAction(MainWindow)
        self.actionI_O_console.setEnabled(False)
        self.actionI_O_console.setObjectName(_fromUtf8("actionI_O_console"))
        self.actionConnect = QtGui.QAction(MainWindow)
        self.actionConnect.setObjectName(_fromUtf8("actionConnect"))
        self.actionDisconnect = QtGui.QAction(MainWindow)
        self.actionDisconnect.setEnabled(False)
        self.actionDisconnect.setObjectName(_fromUtf8("actionDisconnect"))
        self.actionPosition_list = QtGui.QAction(MainWindow)
        self.actionPosition_list.setEnabled(False)
        self.actionPosition_list.setObjectName(_fromUtf8("actionPosition_list"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.menuFile.addAction(self.actionManual_control)
        self.menuFile.addAction(self.actionEditor)
        self.menuFile.addAction(self.actionPosition_list)
        self.menuFile.addAction(self.actionI_O_console)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuSetting.addAction(self.actionSerial_port)
        self.menuAbout.addAction(self.actionAbout)
        self.menuRun.addAction(self.actionConnect)
        self.menuRun.addAction(self.actionDisconnect)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.en_send, self.pb_send)
        MainWindow.setTabOrder(self.pb_send, self.lw_received)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.dockWidget.setWindowTitle(_translate("MainWindow", "Comunication terminal", None))
        self.pb_send.setText(_translate("MainWindow", "Send", None))
        self.pb_clear.setText(_translate("MainWindow", "Clear", None))
        self.control_dock.setWindowTitle(_translate("MainWindow", "Control", None))
        self.pb_connect.setText(_translate("MainWindow", "Connect", None))
        self.pb_disconnect.setText(_translate("MainWindow", "Disconnect", None))
        self.pb_manualControl.setToolTip(_translate("MainWindow", "Open/close manual control window", None))
        self.pb_manualControl.setText(_translate("MainWindow", "Manual control", None))
        self.pb_editor.setToolTip(_translate("MainWindow", "Open/close program editor", None))
        self.pb_editor.setText(_translate("MainWindow", "Program editor", None))
        self.pb_postionList.setToolTip(_translate("MainWindow", "Open/close position list table", None))
        self.pb_postionList.setText(_translate("MainWindow", "Position list", None))
        self.pb_IOconsole.setToolTip(_translate("MainWindow", "Not implemented yet", None))
        self.pb_IOconsole.setText(_translate("MainWindow", "I/O console", None))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting", None))
        self.menuAbout.setTitle(_translate("MainWindow", "Help", None))
        self.menuRun.setTitle(_translate("MainWindow", "Run", None))
        self.actionSerial_port.setText(_translate("MainWindow", "Serial port", None))
        self.actionManual_control.setText(_translate("MainWindow", "Manual control", None))
        self.actionEditor.setText(_translate("MainWindow", "Program editor", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionI_O_console.setText(_translate("MainWindow", "I/O console", None))
        self.actionConnect.setText(_translate("MainWindow", "Connect", None))
        self.actionDisconnect.setText(_translate("MainWindow", "Disconnect", None))
        self.actionPosition_list.setText(_translate("MainWindow", "Position list", None))
        self.actionAbout.setText(_translate("MainWindow", "About...", None))

