# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manualControl.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ManualControl(object):
    def setupUi(self, ManualControl):
        ManualControl.setObjectName(_fromUtf8("ManualControl"))
        ManualControl.resize(437, 320)
        self.horizontalLayout = QtGui.QHBoxLayout(ManualControl)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frame = QtGui.QFrame(ManualControl)
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.verticalLayout = QtGui.QVBoxLayout(self.frame)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.frame)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Ignored, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(150, 0))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.xyz = QtGui.QWidget()
        self.xyz.setObjectName(_fromUtf8("xyz"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.xyz)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.frame_8 = QtGui.QFrame(self.xyz)
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.gridLayout_4 = QtGui.QGridLayout(self.frame_8)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 0, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem1, 1, 3, 1, 1)
        self.sb_xyzY = QtGui.QSpinBox(self.frame_8)
        self.sb_xyzY.setMinimum(-30)
        self.sb_xyzY.setMaximum(30)
        self.sb_xyzY.setObjectName(_fromUtf8("sb_xyzY"))
        self.gridLayout_4.addWidget(self.sb_xyzY, 1, 2, 1, 1)
        self.label = QtGui.QLabel(self.frame_8)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_4.addWidget(self.label, 0, 1, 1, 1)
        self.sb_xyzZ = QtGui.QSpinBox(self.frame_8)
        self.sb_xyzZ.setMinimum(-30)
        self.sb_xyzZ.setMaximum(30)
        self.sb_xyzZ.setObjectName(_fromUtf8("sb_xyzZ"))
        self.gridLayout_4.addWidget(self.sb_xyzZ, 2, 2, 1, 1)
        self.label_5 = QtGui.QLabel(self.frame_8)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_4.addWidget(self.label_5, 2, 1, 1, 1)
        self.sb_xyzX = QtGui.QSpinBox(self.frame_8)
        self.sb_xyzX.setMinimum(-30)
        self.sb_xyzX.setMaximum(30)
        self.sb_xyzX.setObjectName(_fromUtf8("sb_xyzX"))
        self.gridLayout_4.addWidget(self.sb_xyzX, 0, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.frame_8)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_4.addWidget(self.label_4, 1, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem2, 2, 0, 1, 1)
        spacerItem3 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 1, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem4, 0, 0, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem5, 2, 3, 1, 1)
        self.verticalLayout_5.addWidget(self.frame_8)
        self.pb_moveXYZ = QtGui.QPushButton(self.xyz)
        self.pb_moveXYZ.setObjectName(_fromUtf8("pb_moveXYZ"))
        self.verticalLayout_5.addWidget(self.pb_moveXYZ)
        self.tabWidget.addTab(self.xyz, _fromUtf8(""))
        self.joint = QtGui.QWidget()
        self.joint.setObjectName(_fromUtf8("joint"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.joint)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.frame_6 = QtGui.QFrame(self.joint)
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.gridLayout_3 = QtGui.QGridLayout(self.frame_6)
        self.gridLayout_3.setVerticalSpacing(30)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.rb_joint_1 = QtGui.QRadioButton(self.frame_6)
        self.rb_joint_1.setObjectName(_fromUtf8("rb_joint_1"))
        self.gridLayout_3.addWidget(self.rb_joint_1, 0, 0, 1, 1)
        self.rb_joint_4 = QtGui.QRadioButton(self.frame_6)
        self.rb_joint_4.setObjectName(_fromUtf8("rb_joint_4"))
        self.gridLayout_3.addWidget(self.rb_joint_4, 0, 1, 1, 1)
        self.rb_joint_2 = QtGui.QRadioButton(self.frame_6)
        self.rb_joint_2.setObjectName(_fromUtf8("rb_joint_2"))
        self.gridLayout_3.addWidget(self.rb_joint_2, 1, 0, 1, 1)
        self.rb_joint_5 = QtGui.QRadioButton(self.frame_6)
        self.rb_joint_5.setObjectName(_fromUtf8("rb_joint_5"))
        self.gridLayout_3.addWidget(self.rb_joint_5, 1, 1, 1, 1)
        self.rb_joint_3 = QtGui.QRadioButton(self.frame_6)
        self.rb_joint_3.setObjectName(_fromUtf8("rb_joint_3"))
        self.gridLayout_3.addWidget(self.rb_joint_3, 2, 0, 1, 1)
        self.rb_joint_6 = QtGui.QRadioButton(self.frame_6)
        self.rb_joint_6.setObjectName(_fromUtf8("rb_joint_6"))
        self.gridLayout_3.addWidget(self.rb_joint_6, 2, 1, 1, 1)
        self.rb_joint_6.raise_()
        self.rb_joint_4.raise_()
        self.rb_joint_5.raise_()
        self.rb_joint_2.raise_()
        self.rb_joint_3.raise_()
        self.rb_joint_1.raise_()
        self.verticalLayout_4.addWidget(self.frame_6)
        self.frame_7 = QtGui.QFrame(self.joint)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.frame_7)
        self.horizontalLayout_4.setContentsMargins(0, -1, 0, -1)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.scroll_joint = QtGui.QScrollBar(self.frame_7)
        self.scroll_joint.setMinimum(-30)
        self.scroll_joint.setMaximum(30)
        self.scroll_joint.setOrientation(QtCore.Qt.Horizontal)
        self.scroll_joint.setObjectName(_fromUtf8("scroll_joint"))
        self.horizontalLayout_4.addWidget(self.scroll_joint)
        self.l_scroll_joint = QtGui.QLabel(self.frame_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_scroll_joint.sizePolicy().hasHeightForWidth())
        self.l_scroll_joint.setSizePolicy(sizePolicy)
        self.l_scroll_joint.setMinimumSize(QtCore.QSize(15, 0))
        self.l_scroll_joint.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.l_scroll_joint.setObjectName(_fromUtf8("l_scroll_joint"))
        self.horizontalLayout_4.addWidget(self.l_scroll_joint)
        self.verticalLayout_4.addWidget(self.frame_7)
        self.pb_moveJoint = QtGui.QPushButton(self.joint)
        self.pb_moveJoint.setObjectName(_fromUtf8("pb_moveJoint"))
        self.verticalLayout_4.addWidget(self.pb_moveJoint)
        self.tabWidget.addTab(self.joint, _fromUtf8(""))
        self.tool = QtGui.QWidget()
        self.tool.setObjectName(_fromUtf8("tool"))
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.tool)
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.frame_9 = QtGui.QFrame(self.tool)
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.gridLayout_5 = QtGui.QGridLayout(self.frame_9)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.sb_toolX = QtGui.QSpinBox(self.frame_9)
        self.sb_toolX.setMinimum(-30)
        self.sb_toolX.setMaximum(30)
        self.sb_toolX.setObjectName(_fromUtf8("sb_toolX"))
        self.gridLayout_5.addWidget(self.sb_toolX, 0, 2, 1, 1)
        self.sb_toolY = QtGui.QSpinBox(self.frame_9)
        self.sb_toolY.setMinimum(-30)
        self.sb_toolY.setMaximum(30)
        self.sb_toolY.setObjectName(_fromUtf8("sb_toolY"))
        self.gridLayout_5.addWidget(self.sb_toolY, 1, 2, 1, 1)
        self.label_11 = QtGui.QLabel(self.frame_9)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_5.addWidget(self.label_11, 0, 1, 1, 1)
        self.sb_toolZ = QtGui.QSpinBox(self.frame_9)
        self.sb_toolZ.setMinimum(-30)
        self.sb_toolZ.setMaximum(30)
        self.sb_toolZ.setObjectName(_fromUtf8("sb_toolZ"))
        self.gridLayout_5.addWidget(self.sb_toolZ, 2, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.frame_9)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_5.addWidget(self.label_12, 2, 1, 1, 1)
        self.label_13 = QtGui.QLabel(self.frame_9)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_5.addWidget(self.label_13, 1, 1, 1, 1)
        spacerItem6 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem6, 0, 3, 1, 1)
        spacerItem7 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem7, 1, 3, 1, 1)
        spacerItem8 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem8, 2, 3, 1, 1)
        spacerItem9 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem9, 2, 0, 1, 1)
        spacerItem10 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem10, 1, 0, 1, 1)
        spacerItem11 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem11, 0, 0, 1, 1)
        self.verticalLayout_6.addWidget(self.frame_9)
        self.pb_moveTool = QtGui.QPushButton(self.tool)
        self.pb_moveTool.setObjectName(_fromUtf8("pb_moveTool"))
        self.verticalLayout_6.addWidget(self.pb_moveTool)
        self.tabWidget.addTab(self.tool, _fromUtf8(""))
        self.verticalLayout.addWidget(self.tabWidget)
        self.horizontalLayout.addWidget(self.frame)
        self.frame_2 = QtGui.QFrame(ManualControl)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.frame_3 = QtGui.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.frame_4 = QtGui.QFrame(self.frame_3)
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.frame_4)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pb_open_hand = QtGui.QPushButton(self.frame_4)
        self.pb_open_hand.setObjectName(_fromUtf8("pb_open_hand"))
        self.horizontalLayout_2.addWidget(self.pb_open_hand)
        self.pb_close_hand = QtGui.QPushButton(self.frame_4)
        self.pb_close_hand.setObjectName(_fromUtf8("pb_close_hand"))
        self.horizontalLayout_2.addWidget(self.pb_close_hand)
        self.verticalLayout_3.addWidget(self.frame_4)
        self.line = QtGui.QFrame(self.frame_3)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayout_3.addWidget(self.line)
        self.frame_5 = QtGui.QFrame(self.frame_3)
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame_5)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.scroll_speed = QtGui.QScrollBar(self.frame_5)
        self.scroll_speed.setMaximum(20)
        self.scroll_speed.setOrientation(QtCore.Qt.Horizontal)
        self.scroll_speed.setObjectName(_fromUtf8("scroll_speed"))
        self.horizontalLayout_3.addWidget(self.scroll_speed)
        self.l_scroll_speed = QtGui.QLabel(self.frame_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.l_scroll_speed.sizePolicy().hasHeightForWidth())
        self.l_scroll_speed.setSizePolicy(sizePolicy)
        self.l_scroll_speed.setMinimumSize(QtCore.QSize(15, 0))
        self.l_scroll_speed.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.l_scroll_speed.setObjectName(_fromUtf8("l_scroll_speed"))
        self.horizontalLayout_3.addWidget(self.l_scroll_speed)
        self.verticalLayout_3.addWidget(self.frame_5)
        self.pb_setSpeed = QtGui.QPushButton(self.frame_3)
        self.pb_setSpeed.setObjectName(_fromUtf8("pb_setSpeed"))
        self.verticalLayout_3.addWidget(self.pb_setSpeed)
        self.verticalLayout_2.addWidget(self.frame_3)
        self.gb_savePostion = QtGui.QGroupBox(self.frame_2)
        self.gb_savePostion.setObjectName(_fromUtf8("gb_savePostion"))
        self.gridLayout = QtGui.QGridLayout(self.gb_savePostion)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.label_2 = QtGui.QLabel(self.gb_savePostion)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.sb_savePos = QtGui.QSpinBox(self.gb_savePostion)
        self.sb_savePos.setMinimum(1)
        self.sb_savePos.setMaximum(999)
        self.sb_savePos.setObjectName(_fromUtf8("sb_savePos"))
        self.gridLayout.addWidget(self.sb_savePos, 0, 1, 1, 1)
        self.pb_savePos = QtGui.QPushButton(self.gb_savePostion)
        self.pb_savePos.setObjectName(_fromUtf8("pb_savePos"))
        self.gridLayout.addWidget(self.pb_savePos, 1, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.gb_savePostion)
        self.gb_movePosition = QtGui.QGroupBox(self.frame_2)
        self.gb_movePosition.setObjectName(_fromUtf8("gb_movePosition"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gb_movePosition)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_3 = QtGui.QLabel(self.gb_movePosition)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_2.addWidget(self.label_3, 0, 0, 1, 1)
        self.sb_movePos = QtGui.QSpinBox(self.gb_movePosition)
        self.sb_movePos.setMinimum(1)
        self.sb_movePos.setMaximum(999)
        self.sb_movePos.setObjectName(_fromUtf8("sb_movePos"))
        self.gridLayout_2.addWidget(self.sb_movePos, 0, 1, 1, 1)
        self.pb_movePos = QtGui.QPushButton(self.gb_movePosition)
        self.pb_movePos.setObjectName(_fromUtf8("pb_movePos"))
        self.gridLayout_2.addWidget(self.pb_movePos, 1, 0, 1, 2)
        self.verticalLayout_2.addWidget(self.gb_movePosition)
        self.horizontalLayout.addWidget(self.frame_2)

        self.retranslateUi(ManualControl)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QObject.connect(self.scroll_speed, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.l_scroll_speed.setNum)
        QtCore.QObject.connect(self.scroll_joint, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.l_scroll_joint.setNum)
        QtCore.QMetaObject.connectSlotsByName(ManualControl)

    def retranslateUi(self, ManualControl):
        ManualControl.setWindowTitle(_translate("ManualControl", "Manual control", None))
        self.label.setText(_translate("ManualControl", "X:", None))
        self.label_5.setText(_translate("ManualControl", "Z:", None))
        self.label_4.setText(_translate("ManualControl", "Y:", None))
        self.pb_moveXYZ.setText(_translate("ManualControl", "Move XYZ", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.xyz), _translate("ManualControl", "XYZ", None))
        self.rb_joint_1.setText(_translate("ManualControl", "Joint 1", None))
        self.rb_joint_4.setText(_translate("ManualControl", "Joint 4", None))
        self.rb_joint_2.setText(_translate("ManualControl", "Joint 2", None))
        self.rb_joint_5.setText(_translate("ManualControl", "Joint 5", None))
        self.rb_joint_3.setText(_translate("ManualControl", "Joint 3", None))
        self.rb_joint_6.setText(_translate("ManualControl", "Joint 6", None))
        self.l_scroll_joint.setText(_translate("ManualControl", "0", None))
        self.pb_moveJoint.setText(_translate("ManualControl", "Move Joint", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.joint), _translate("ManualControl", "Joint", None))
        self.label_11.setText(_translate("ManualControl", "X:", None))
        self.label_12.setText(_translate("ManualControl", "Z:", None))
        self.label_13.setText(_translate("ManualControl", "Y:", None))
        self.pb_moveTool.setText(_translate("ManualControl", "Move straight", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tool), _translate("ManualControl", "Straight", None))
        self.pb_open_hand.setText(_translate("ManualControl", "Close hand", None))
        self.pb_close_hand.setText(_translate("ManualControl", "Open hand", None))
        self.l_scroll_speed.setText(_translate("ManualControl", "0", None))
        self.pb_setSpeed.setText(_translate("ManualControl", "Set speed", None))
        self.gb_savePostion.setTitle(_translate("ManualControl", "Save postion", None))
        self.label_2.setText(_translate("ManualControl", "Postion No.", None))
        self.pb_savePos.setText(_translate("ManualControl", "Save", None))
        self.gb_movePosition.setTitle(_translate("ManualControl", "Move to postion", None))
        self.label_3.setText(_translate("ManualControl", "Postion No.", None))
        self.pb_movePos.setText(_translate("ManualControl", "Move", None))

