# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(724, 516)
        MainWindow.setAnimated(False)
        MainWindow.setDockOptions(QtGui.QMainWindow.AllowNestedDocks|QtGui.QMainWindow.AllowTabbedDocks)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gb_connection = QtGui.QGroupBox(self.centralwidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gb_connection.sizePolicy().hasHeightForWidth())
        self.gb_connection.setSizePolicy(sizePolicy)
        self.gb_connection.setMaximumSize(QtCore.QSize(16777215, 100))
        self.gb_connection.setObjectName(_fromUtf8("gb_connection"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.gb_connection)
        self.horizontalLayout.setContentsMargins(9, 3, 9, 4)
        self.horizontalLayout.setSpacing(3)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.l_connectionStatus = QtGui.QLabel(self.gb_connection)
        self.l_connectionStatus.setObjectName(_fromUtf8("l_connectionStatus"))
        self.horizontalLayout.addWidget(self.l_connectionStatus)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.line = QtGui.QFrame(self.gb_connection)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.line.sizePolicy().hasHeightForWidth())
        self.line.setSizePolicy(sizePolicy)
        self.line.setFrameShape(QtGui.QFrame.VLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.horizontalLayout.addWidget(self.line)
        self.l_portName = QtGui.QLabel(self.gb_connection)
        self.l_portName.setObjectName(_fromUtf8("l_portName"))
        self.horizontalLayout.addWidget(self.l_portName)
        self.line_2 = QtGui.QFrame(self.gb_connection)
        self.line_2.setFrameShape(QtGui.QFrame.VLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.horizontalLayout.addWidget(self.line_2)
        self.l_portParameters = QtGui.QLabel(self.gb_connection)
        self.l_portParameters.setObjectName(_fromUtf8("l_portParameters"))
        self.horizontalLayout.addWidget(self.l_portParameters)
        self.gridLayout_2.addWidget(self.gb_connection, 0, 0, 1, 3)
        self.gb_controlButtons = QtGui.QGroupBox(self.centralwidget)
        self.gb_controlButtons.setObjectName(_fromUtf8("gb_controlButtons"))
        self.verticalLayout = QtGui.QVBoxLayout(self.gb_controlButtons)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.pb_connect = QtGui.QPushButton(self.gb_controlButtons)
        self.pb_connect.setObjectName(_fromUtf8("pb_connect"))
        self.verticalLayout.addWidget(self.pb_connect)
        self.pb_disconnect = QtGui.QPushButton(self.gb_controlButtons)
        self.pb_disconnect.setEnabled(False)
        self.pb_disconnect.setObjectName(_fromUtf8("pb_disconnect"))
        self.verticalLayout.addWidget(self.pb_disconnect)
        self.line_3 = QtGui.QFrame(self.gb_controlButtons)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.verticalLayout.addWidget(self.line_3)
        self.pb_manualControl = QtGui.QPushButton(self.gb_controlButtons)
        self.pb_manualControl.setEnabled(False)
        self.pb_manualControl.setObjectName(_fromUtf8("pb_manualControl"))
        self.verticalLayout.addWidget(self.pb_manualControl)
        self.pb_editor = QtGui.QPushButton(self.gb_controlButtons)
        self.pb_editor.setEnabled(False)
        self.pb_editor.setObjectName(_fromUtf8("pb_editor"))
        self.verticalLayout.addWidget(self.pb_editor)
        self.pb_IOconsole = QtGui.QPushButton(self.gb_controlButtons)
        self.pb_IOconsole.setEnabled(False)
        self.pb_IOconsole.setObjectName(_fromUtf8("pb_IOconsole"))
        self.verticalLayout.addWidget(self.pb_IOconsole)
        self.pb_postionList = QtGui.QPushButton(self.gb_controlButtons)
        self.pb_postionList.setEnabled(False)
        self.pb_postionList.setObjectName(_fromUtf8("pb_postionList"))
        self.verticalLayout.addWidget(self.pb_postionList)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.gridLayout_2.addWidget(self.gb_controlButtons, 1, 2, 1, 1)
        self.gb_communication = QtGui.QGroupBox(self.centralwidget)
        self.gb_communication.setEnabled(False)
        self.gb_communication.setAutoFillBackground(False)
        self.gb_communication.setFlat(False)
        self.gb_communication.setCheckable(False)
        self.gb_communication.setObjectName(_fromUtf8("gb_communication"))
        self.gridLayout = QtGui.QGridLayout(self.gb_communication)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.en_send = QtGui.QLineEdit(self.gb_communication)
        self.en_send.setMinimumSize(QtCore.QSize(100, 0))
        self.en_send.setObjectName(_fromUtf8("en_send"))
        self.gridLayout.addWidget(self.en_send, 1, 0, 1, 1)
        self.pb_send = QtGui.QPushButton(self.gb_communication)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_send.sizePolicy().hasHeightForWidth())
        self.pb_send.setSizePolicy(sizePolicy)
        self.pb_send.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pb_send.setBaseSize(QtCore.QSize(30, 0))
        self.pb_send.setObjectName(_fromUtf8("pb_send"))
        self.gridLayout.addWidget(self.pb_send, 1, 1, 1, 1)
        self.pb_clear = QtGui.QPushButton(self.gb_communication)
        self.pb_clear.setMaximumSize(QtCore.QSize(40, 16777215))
        self.pb_clear.setObjectName(_fromUtf8("pb_clear"))
        self.gridLayout.addWidget(self.pb_clear, 1, 2, 1, 1)
        self.lw_received = QtGui.QListWidget(self.gb_communication)
        self.lw_received.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.lw_received.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.lw_received.setObjectName(_fromUtf8("lw_received"))
        self.gridLayout.addWidget(self.lw_received, 0, 0, 1, 3)
        self.gridLayout.setColumnStretch(0, 10)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setColumnStretch(2, 1)
        self.gridLayout_2.addWidget(self.gb_communication, 1, 0, 1, 1)
        self.gb_mdi = QtGui.QGroupBox(self.centralwidget)
        self.gb_mdi.setEnabled(False)
        self.gb_mdi.setObjectName(_fromUtf8("gb_mdi"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gb_mdi)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.mdiArea = QtGui.QMdiArea(self.gb_mdi)
        self.mdiArea.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.mdiArea.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        brush = QtGui.QBrush(QtGui.QColor(202, 202, 202))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.mdiArea.setBackground(brush)
        self.mdiArea.setObjectName(_fromUtf8("mdiArea"))
        self.verticalLayout_2.addWidget(self.mdiArea)
        self.gridLayout_2.addWidget(self.gb_mdi, 1, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 724, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuSetting = QtGui.QMenu(self.menubar)
        self.menuSetting.setObjectName(_fromUtf8("menuSetting"))
        self.menuAbout = QtGui.QMenu(self.menubar)
        self.menuAbout.setObjectName(_fromUtf8("menuAbout"))
        self.menuRun = QtGui.QMenu(self.menubar)
        self.menuRun.setObjectName(_fromUtf8("menuRun"))
        self.menuEditor = QtGui.QMenu(self.menubar)
        self.menuEditor.setObjectName(_fromUtf8("menuEditor"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionSerial_port = QtGui.QAction(MainWindow)
        self.actionSerial_port.setObjectName(_fromUtf8("actionSerial_port"))
        self.actionManual_control = QtGui.QAction(MainWindow)
        self.actionManual_control.setEnabled(False)
        self.actionManual_control.setObjectName(_fromUtf8("actionManual_control"))
        self.actionEditor = QtGui.QAction(MainWindow)
        self.actionEditor.setEnabled(False)
        self.actionEditor.setObjectName(_fromUtf8("actionEditor"))
        self.actionExit = QtGui.QAction(MainWindow)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionI_O_console = QtGui.QAction(MainWindow)
        self.actionI_O_console.setEnabled(False)
        self.actionI_O_console.setObjectName(_fromUtf8("actionI_O_console"))
        self.actionAbout_Qt = QtGui.QAction(MainWindow)
        self.actionAbout_Qt.setObjectName(_fromUtf8("actionAbout_Qt"))
        self.actionAbout_program = QtGui.QAction(MainWindow)
        self.actionAbout_program.setObjectName(_fromUtf8("actionAbout_program"))
        self.actionAbout_author = QtGui.QAction(MainWindow)
        self.actionAbout_author.setObjectName(_fromUtf8("actionAbout_author"))
        self.actionConnect = QtGui.QAction(MainWindow)
        self.actionConnect.setObjectName(_fromUtf8("actionConnect"))
        self.actionDisconnect = QtGui.QAction(MainWindow)
        self.actionDisconnect.setEnabled(False)
        self.actionDisconnect.setObjectName(_fromUtf8("actionDisconnect"))
        self.actionPosition_list = QtGui.QAction(MainWindow)
        self.actionPosition_list.setEnabled(False)
        self.actionPosition_list.setObjectName(_fromUtf8("actionPosition_list"))
        self.menuFile.addAction(self.actionManual_control)
        self.menuFile.addAction(self.actionEditor)
        self.menuFile.addAction(self.actionI_O_console)
        self.menuFile.addAction(self.actionPosition_list)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuSetting.addAction(self.actionSerial_port)
        self.menuAbout.addAction(self.actionAbout_program)
        self.menuAbout.addAction(self.actionAbout_Qt)
        self.menuAbout.addAction(self.actionAbout_author)
        self.menuRun.addAction(self.actionConnect)
        self.menuRun.addAction(self.actionDisconnect)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuRun.menuAction())
        self.menubar.addAction(self.menuSetting.menuAction())
        self.menubar.addAction(self.menuAbout.menuAction())
        self.menubar.addAction(self.menuEditor.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.en_send, self.pb_connect)
        MainWindow.setTabOrder(self.pb_connect, self.pb_disconnect)
        MainWindow.setTabOrder(self.pb_disconnect, self.pb_manualControl)
        MainWindow.setTabOrder(self.pb_manualControl, self.pb_editor)
        MainWindow.setTabOrder(self.pb_editor, self.pb_IOconsole)
        MainWindow.setTabOrder(self.pb_IOconsole, self.pb_send)
        MainWindow.setTabOrder(self.pb_send, self.lw_received)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.gb_connection.setTitle(_translate("MainWindow", "Connection status:", None))
        self.l_connectionStatus.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">Disconnected</span></p></body></html>", None))
        self.l_portName.setText(_translate("MainWindow", "<html><head/><body><p>COM1</p></body></html>", None))
        self.l_portParameters.setText(_translate("MainWindow", "<html><head/><body><p>9600,E,8,2</p></body></html>", None))
        self.gb_controlButtons.setTitle(_translate("MainWindow", "Control", None))
        self.pb_connect.setText(_translate("MainWindow", "Connect", None))
        self.pb_disconnect.setText(_translate("MainWindow", "Disconnect", None))
        self.pb_manualControl.setText(_translate("MainWindow", "Manual control", None))
        self.pb_editor.setText(_translate("MainWindow", "Program editor", None))
        self.pb_IOconsole.setText(_translate("MainWindow", "I/O console", None))
        self.pb_postionList.setText(_translate("MainWindow", "Position list", None))
        self.gb_communication.setTitle(_translate("MainWindow", "Communication terminal", None))
        self.pb_send.setText(_translate("MainWindow", "Send", None))
        self.pb_clear.setText(_translate("MainWindow", "Clear", None))
        self.gb_mdi.setTitle(_translate("MainWindow", "Workspace", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuSetting.setTitle(_translate("MainWindow", "Setting", None))
        self.menuAbout.setTitle(_translate("MainWindow", "Help", None))
        self.menuRun.setTitle(_translate("MainWindow", "Run", None))
        self.menuEditor.setTitle(_translate("MainWindow", "Editor", None))
        self.actionSerial_port.setText(_translate("MainWindow", "Serial port", None))
        self.actionManual_control.setText(_translate("MainWindow", "Manual control", None))
        self.actionEditor.setText(_translate("MainWindow", "Program editor", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionI_O_console.setText(_translate("MainWindow", "I/O console", None))
        self.actionAbout_Qt.setText(_translate("MainWindow", "About Qt", None))
        self.actionAbout_program.setText(_translate("MainWindow", "About program", None))
        self.actionAbout_author.setText(_translate("MainWindow", "About author", None))
        self.actionConnect.setText(_translate("MainWindow", "Connect", None))
        self.actionDisconnect.setText(_translate("MainWindow", "Disconnect", None))
        self.actionPosition_list.setText(_translate("MainWindow", "Position list", None))

